# https://colab.research.google.com/

# Apprendre à coder en Python pour l'Intelligence Artificielle
## Episode 6 - Les libraries Numpy et Pandas

<p align="center">
<a href="https://www.youtube.com/watch?v=qMGjh6rKIgw" target="_blank" ><img  src="https://github.com/anisayari/Youtube-apprendre-python-intelligence-artificielle/blob/master/%236%20-%20Les%20libraries%20Numpy%20et%20Pandas/cover-serie-6.png?raw=true" width="800" height="auto"/></a>
</p>




<img  src="https://miro.medium.com/max/645/0*1B31atH5V153v5JP.jpg" width="800" height="auto"/>



<img  src="https://blog.equinix.com/wp-content/uploads/2016/08/apps-big-data.jpg" width="800" height="auto"/>

# Numpy

Librarie pour calculs sceintifique en Python.

<a href="https://numpy.org/devdocs/" target="_blank" >Documentation  </a>

<a href="https://numpy.org/" target="_blank" ><img  src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" width="400" height="auto"/></a>

In [2]:
#Créer un ndarray (array)
#Array , multiple elements and axes (ie.ligne, colonne)
import numpy as np
#np.arange(n) #créer un array de n elements et 1axes
#np.zeros(i,j) Créer un array de shape ixj rempli de 0
#np.ones(i,j) Créer un array de shape ixj rempli de 1
#np.eye(i,j) créer une matrice identité de dimension i,j
#np.random.rand(n) créer un array de dimension 1 aléatoire:
#np.random.random(size=(i,j)) créer un array de dimension i,j random

In [2]:
#np.array (nb : possible de créer des nombres complexes dtype=complex)
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#np.arange(n) #créer un array de n elements et 1axes
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#np.arange(n).reshape(i, j) reformate l'array en array de i element et j axes
np.arange(8).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
#np.zeros(i,j) Créer un array de shape ixj rempli de 0
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
#np.random.rand(n) créer un array de dimension 1 aléatoire de n elements
np.random.rand(10)

array([0.12837781, 0.76751735, 0.68890603, 0.43335721, 0.87078696,
       0.23026943, 0.53842735, 0.14495675, 0.93173428, 0.27374526])

In [ ]:
#np.random.random(size=(i,j)) créer un array de dimension i,j random
np.random.random(size=(3,2))

array([[0.82636998, 0.11492714],
       [0.93691523, 0.22599347],
       [0.58950355, 0.08020352]])

In [13]:
#indexing
#Marche de la même facon que les listes pour un array de dimension 1
# en multidimension un index est représenté par un tuple array[(i1:j1),(i2:j2)] (i1,j1) = lignes, (i2,j2) = colonnes

myArray = np.random.rand(5)
print(myArray)
print(type(myArray))
print(myArray[3])

myArray_multidimension = np.random.rand(6).reshape(3,2)
print(myArray_multidimension)
print(myArray_multidimension[1,1])

[0.61002388 0.68451562 0.96949713 0.53411868 0.73132627]
<class 'numpy.ndarray'>
0.5341186753490745
[[0.86634274 0.29509623]
 [0.02506262 0.70209771]
 [0.58616413 0.64150932]]
0.702097711925232


In [ ]:
#np.shape, np.ndim, np.size
print(myArray_multidimension.shape) #forme d'aray (nombre d'elements, nombre d'axes)
print(myArray_multidimension.ndim) #le nombre de dimension
print(myArray_multidimension.size) #le nombre total déelement dans mon array

(3, 2)
2
6


In [ ]:
#fonctions mathématique np.cos, np.log, np.exp, np.sqrt etc...

myArray = np.arange(10).reshape(5,2)
print(myArray)
print(np.cos(myArray))
print(np.exp(myArray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]
 [-0.14550003 -0.91113026]]
[[1.00000000e+00 2.71828183e+00]
 [7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03]]


In [ ]:
np.var(myArray) #variance

8.25

In [ ]:
#fonctions utiles np.sum , np.min, np.max, np.mean
print(myArray)
print(myArray.min())
print(myArray.max())
print(np.max(myArray))
print(np.mean(myArray))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
0
9
9
4.5


<a href='https://fr.wikipedia.org/wiki/Matrice_(math%C3%A9matiques)'>  Les matrices </a>

<a href='https://fr.wikipedia.org/wiki/Produit_matriciel'> Calcul matriciel (Article Wikipedia) </a>

<img  src="https://wikimedia.org/api/rest_v1/media/math/render/svg/840716c2745c63bd10c38a0b5ecac966faf0b1ff" width="400" height="auto"/>
<img  src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Matrix_multiplication_diagram.svg/188px-Matrix_multiplication_diagram.svg.png
" width="100" height="auto"/>


In [3]:
# produit elements par element *
A = np.arange(16).reshape(4,4)
print(A)
B = np.random.rand(16).reshape(4,4)
print(B)

print(A*B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.75218534 0.2511852  0.49064698 0.40724091]
 [0.63379132 0.9219811  0.26975074 0.77182296]
 [0.27906193 0.17298888 0.82318489 0.08551174]
 [0.63581583 0.18528335 0.84469325 0.0795661 ]]
[[ 0.          0.2511852   0.98129396  1.22172273]
 [ 2.53516529  4.60990549  1.61850444  5.40276073]
 [ 2.23249545  1.55689988  8.23184886  0.94062915]
 [ 7.62978994  2.40868361 11.82570544  1.19349149]]


In [ ]:
# produit matriciel @ ou array1.dot(array2)

print(A @ B)
print(A.dot(B))

[[ 3.1512708   0.74353752  1.43028642  2.38044077]
 [ 9.08712624  5.1363223   6.3931383  10.28444804]
 [15.02298167  9.52910707 11.35599019 18.18845531]
 [20.95883711 13.92189184 16.31884207 26.09246258]]
[[ 3.1512708   0.74353752  1.43028642  2.38044077]
 [ 9.08712624  5.1363223   6.3931383  10.28444804]
 [15.02298167  9.52910707 11.35599019 18.18845531]
 [20.95883711 13.92189184 16.31884207 26.09246258]]


In [ ]:
#Transposé .T ou np.transpose()
print(A)
print(A.T)
print(np.transpose(A))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [4]:
#Matrice inversible https://fr.wikipedia.org/wiki/Matrice_inversible
#np.linalg.inv(matrix) matrix carré a non singulière

np.linalg.inv(np.random.rand(9).reshape(3,3))

array([[ 0.4275547 ,  1.49866595, -2.01492169],
       [-0.68689108, -0.44081997,  2.54582766],
       [ 1.893579  , -0.29412177, -1.39525916]])

# Pandas

Librarie de manipulation et d'analyse de données pour Python.

<a href="https://pandas.pydata.org/docs/user_guide/index.html" target="_blank" >Documentation  </a>

<a href="https://pandas.pydata.org/" target="_blank" ><img  src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1200px-Pandas_logo.svg.png" width="400" height="auto"/></a>


<img  src="https://pandas.pydata.org/docs/_images/01_table_dataframe.svg" width="400" height="auto"/>


<img  src="https://pandas.pydata.org/docs/_images/02_io_readwrite.svg" width="400" height="auto"/>


In [5]:
#Les objets en pandas - Series et DataFrame
#pd.Series(list/array,index=[...])
#pd.Series(dict)

import pandas as pd

print(pd.Series(np.array([1,2,3])))
print(pd.Series([5,6,7]))

0    1
1    2
2    3
dtype: int64
0    5
1    6
2    7
dtype: int64


In [ ]:
#pd.DataFrame(array, index=[...])
#pd.DataFrame(dict avec list comme value )

pd.DataFrame({'colonne1':[1,2,3],
              'colonne2':[5,4,3]})

colonne1  colonne2
0         1         5
1         2         4
2         3         3

In [6]:
#df.head(n) afficher les n première lignes de notre DF

df_covid = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-19-2020.csv')
df_covid.head(2)

FIPS     Admin2  Province_State Country_Region          Last_Update  \
0  45001.0  Abbeville  South Carolina             US  2020-04-19 23:41:01   
1  22001.0     Acadia       Louisiana             US  2020-04-19 23:41:01   

         Lat      Long_  Confirmed  Deaths  Recovered  Active  \
0  34.223334 -82.461707         17       0          0      17   
1  30.295065 -92.414197        110       7          0     103   

                    Combined_Key  
0  Abbeville, South Carolina, US  
1          Acadia, Louisiana, US

In [ ]:
#set_index(), reset_index()index=[], reindex(columns=[]), définir un index


df_covid.set_index('Country_Region').head()

FIPS     Admin2  ... Active                   Combined_Key
Country_Region                      ...                                      
US              45001.0  Abbeville  ...     17  Abbeville, South Carolina, US
US              22001.0     Acadia  ...    103          Acadia, Louisiana, US
US              51001.0   Accomack  ...     42         Accomack, Virginia, US
US              16001.0        Ada  ...    588                 Ada, Idaho, US
US              19001.0      Adair  ...      1                Adair, Iowa, US

[5 rows x 11 columns]

In [ ]:
df_covid.head(2)

FIPS     Admin2  ... Active                   Combined_Key
0  45001.0  Abbeville  ...     17  Abbeville, South Carolina, US
1  22001.0     Acadia  ...    103          Acadia, Louisiana, US

[2 rows x 12 columns]

In [ ]:
#enregistrer le changement d'index
#df_covid = df_covid.set_index('Country_Region').head()
df_covid.set_index('Country_Region', inplace=True)
df_covid.head(2)

FIPS     Admin2  ... Active                   Combined_Key
Country_Region                      ...                                      
US              45001.0  Abbeville  ...     17  Abbeville, South Carolina, US
US              22001.0     Acadia  ...    103          Acadia, Louisiana, US

[2 rows x 11 columns]

In [ ]:
df_covid = df_covid.reset_index()
df_covid.head(2)

Country_Region     FIPS  ... Active                   Combined_Key
0             US  45001.0  ...     17  Abbeville, South Carolina, US
1             US  22001.0  ...    103          Acadia, Louisiana, US

[2 rows x 12 columns]

In [ ]:
#renommer des colonnes et index df.rename(columns={old_name:new_name}, index={old_name:new_name})

df_covid.rename(columns={'Admin2':'Admin'}, inplace = True)
df_covid.head(2)

Country_Region     FIPS  ... Active                   Combined_Key
0             US  45001.0  ...     17  Abbeville, South Carolina, US
1             US  22001.0  ...    103          Acadia, Louisiana, US

[2 rows x 12 columns]

In [ ]:
#accéder aux données
# boolean , selectionner certaines données

df_covid['Country_Region'] == 'US'

0        True
1        True
2        True
3        True
4        True
        ...  
3067    False
3068    False
3069    False
3070    False
3071    False
Name: Country_Region, Length: 3072, dtype: bool

In [ ]:
df_covid.shape

(3072, 12)

In [ ]:
df_covid[df_covid['Country_Region'] == 'US']

Country_Region     FIPS  ... Active                   Combined_Key
0                US  45001.0  ...     17  Abbeville, South Carolina, US
1                US  22001.0  ...    103          Acadia, Louisiana, US
2                US  51001.0  ...     42         Accomack, Virginia, US
3                US  16001.0  ...    588                 Ada, Idaho, US
4                US  19001.0  ...      1                Adair, Iowa, US
...             ...      ...  ...    ...                            ...
2829             US     66.0  ...    131                       Guam, US
2856             US     69.0  ...     12   Northern Mariana Islands, US
2862             US     72.0  ...   1151                Puerto Rico, US
2867             US      NaN  ... -70337                  Recovered, US
2885             US     78.0  ...     50             Virgin Islands, US

[2810 rows x 12 columns]

In [ ]:
df_covid[df_covid['Country_Region'] == 'US'].shape

(2810, 14)

In [ ]:
(df_covid[df_covid['Country_Region'] == 'US'].shape[0]/df_covid.shape[0])*100

91.47135416666666

In [ ]:
#df.columns  voir toutes les colonnes de mon df
df_covid.columns

Index(['Country_Region', 'FIPS', 'Admin', 'Province_State', 'Last_Update',
       'Lat', 'Long_', 'Confirmed', 'Deaths', 'Recovered', 'Active',
       'Combined_Key'],
      dtype='object')

In [ ]:
#Series serie[[index]], serie[ : numéro de ligne]
#dataframe accéder à une colone df[colonne]
df_covid[['Country_Region','Active']]


Country_Region  Active
0                     US      17
1                     US     103
2                     US      42
3                     US     588
4                     US       1
...                  ...     ...
3067  West Bank and Gaza     363
3068      Western Sahara       6
3069               Yemen       1
3070              Zambia      25
3071            Zimbabwe      20

[3072 rows x 2 columns]

In [ ]:
#df.loc[nom_index] accéder à la ligne qui correspond a l'index
#df.iloc[numéro_ligne] accede aux valeurs d'un certain numéro de ligne

df_covid.set_index('Country_Region').loc['US']

FIPS      Admin  ... Active                   Combined_Key
Country_Region                      ...                                      
US              45001.0  Abbeville  ...     17  Abbeville, South Carolina, US
US              22001.0     Acadia  ...    103          Acadia, Louisiana, US
US              51001.0   Accomack  ...     42         Accomack, Virginia, US
US              16001.0        Ada  ...    588                 Ada, Idaho, US
US              19001.0      Adair  ...      1                Adair, Iowa, US
...                 ...        ...  ...    ...                            ...
US                 66.0        NaN  ...    131                       Guam, US
US                 69.0        NaN  ...     12   Northern Mariana Islands, US
US                 72.0        NaN  ...   1151                Puerto Rico, US
US                  NaN        NaN  ... -70337                  Recovered, US
US                 78.0        NaN  ...     50             Virgin Islands, US

[2810 rows x 11 columns]

In [ ]:
df_covid.iloc[4:10]

Country_Region     FIPS  Admin  ... Recovered Active         Combined_Key
4             US  19001.0  Adair  ...         0      1      Adair, Iowa, US
5             US  21001.0  Adair  ...         0     50  Adair, Kentucky, US
6             US  29001.0  Adair  ...         0     12  Adair, Missouri, US
7             US  40001.0  Adair  ...         0     40  Adair, Oklahoma, US
8             US   8001.0  Adams  ...         0    880  Adams, Colorado, US
9             US  16003.0  Adams  ...         0      1     Adams, Idaho, US

[6 rows x 12 columns]

In [ ]:
#loc et iloc peuvent prendre plusieurs dimensions entre crochets
#df.loc[nom_index, colonne] loc et iloc peuvent prendre plusieurs dimensions

df_covid.set_index('Country_Region').loc['US',['Active','Deaths']]

Active  Deaths
Country_Region                
US                  17       0
US                 103       7
US                  42       0
US                 588      10
US                   1       0
...                ...     ...
US                 131       5
US                  12       2
US                1151      62
US              -70337       0
US                  50       3

[2810 rows x 2 columns]

In [ ]:
#modifier les données
#df.insert(position, nom_colonne, valeurs) insérer une colonne

df_covid[['Recovered','Active','Deaths']]

Recovered  Active  Deaths
0             0      17       0
1             0     103       7
2             0      42       0
3             0     588      10
4             0       1       0
...         ...     ...     ...
3067         71     363       3
3068          0       6       0
3069          0       1       0
3070         33      25       3
3071          2      20       3

[3072 rows x 3 columns]

In [ ]:
df_covid['sum_all_cases'] = df_covid['Recovered']+df_covid['Active']+df_covid['Deaths']
df_covid

Country_Region     FIPS  ...                   Combined_Key sum_all_cases
0                     US  45001.0  ...  Abbeville, South Carolina, US            17
1                     US  22001.0  ...          Acadia, Louisiana, US           110
2                     US  51001.0  ...         Accomack, Virginia, US            42
3                     US  16001.0  ...                 Ada, Idaho, US           598
4                     US  19001.0  ...                Adair, Iowa, US             1
...                  ...      ...  ...                            ...           ...
3067  West Bank and Gaza      NaN  ...             West Bank and Gaza           437
3068      Western Sahara      NaN  ...                 Western Sahara             6
3069               Yemen      NaN  ...                          Yemen             1
3070              Zambia      NaN  ...                         Zambia            61
3071            Zimbabwe      NaN  ...                       Zimbabwe            25

[3072 rows x 13 columns]

In [ ]:
df_covid.insert(2, 'sum_all_cases2',  df_covid['Recovered']+df_covid['Active']+df_covid['Deaths'])

In [ ]:
df_covid.head()

Country_Region     FIPS  ...                   Combined_Key sum_all_cases
0             US  45001.0  ...  Abbeville, South Carolina, US            17
1             US  22001.0  ...          Acadia, Louisiana, US           110
2             US  51001.0  ...         Accomack, Virginia, US            42
3             US  16001.0  ...                 Ada, Idaho, US           598
4             US  19001.0  ...                Adair, Iowa, US             1

[5 rows x 14 columns]

In [ ]:
#fonctions utiles df.info(), df.describe(), serie.value_counts()
df_covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3072 entries, 0 to 3071
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country_Region  3072 non-null   object 
 1   FIPS            2799 non-null   float64
 2   sum_all_cases2  3072 non-null   int64  
 3   Admin           2803 non-null   object 
 4   Province_State  2891 non-null   object 
 5   Last_Update     3072 non-null   object 
 6   Lat             3012 non-null   float64
 7   Long_           3012 non-null   float64
 8   Confirmed       3072 non-null   int64  
 9   Deaths          3072 non-null   int64  
 10  Recovered       3072 non-null   int64  
 11  Active          3072 non-null   int64  
 12  Combined_Key    3072 non-null   object 
 13  sum_all_cases   3072 non-null   int64  
dtypes: float64(3), int64(6), object(5)
memory usage: 336.1+ KB


In [ ]:
df_covid.describe()

FIPS  sum_all_cases2  ...         Active  sum_all_cases
count   2799.000000     3072.000000  ...    3072.000000    3072.000000
mean   31226.101108      781.698893  ...     524.880208     781.698893
std    17232.001408     7692.970841  ...    5105.785182    7692.970841
min       66.000000        0.000000  ...  -70337.000000       0.000000
25%    18108.000000        5.000000  ...       4.000000       5.000000
50%    29123.000000       18.000000  ...      17.000000      18.000000
75%    46061.000000       90.000000  ...      78.000000      90.000000
max    99999.000000   198674.000000  ...  124249.000000  198674.000000

[8 rows x 9 columns]

In [ ]:
df_covid['Country_Region'].value_counts()

US                       2810
China                      33
Canada                     14
United Kingdom             11
France                     11
                         ... 
Bangladesh                  1
Malta                       1
Sao Tome and Principe       1
Italy                       1
Afghanistan                 1
Name: Country_Region, Length: 185, dtype: int64

In [ ]:
df_covid[df_covid['Country_Region']=='France']

Country_Region  FIPS  ...                       Combined_Key sum_all_cases
2820         France   NaN  ...              French Guiana, France            96
2821         France   NaN  ...           French Polynesia, France            55
2828         France   NaN  ...                 Guadeloupe, France           148
2848         France   NaN  ...                 Martinique, France           163
2849         France   NaN  ...                    Mayotte, France           271
2852         France   NaN  ...              New Caledonia, France            18
2868         France   NaN  ...                    Reunion, France           408
2869         France   NaN  ...           Saint Barthelemy, France             6
2870         France   NaN  ...  Saint Pierre and Miquelon, France             1
2879         France   NaN  ...                  St Martin, France            37
2949         France   NaN  ...                             France        152894

[11 rows x 14 columns]

In [ ]:
# df.copy() copier votre df pour le dupliquer !

df_covid2 = df_covid #df_covid2 va aussi modifier df_covid!!
df_covid2 = df_covid.copy()